print("WELCOME TO ALIEN")
input("you are on THE NOSTROMO with seven other members in your crew. your course is back to earth.")
input("you have just woken up from hypersleep and you gather around the dinner table of the ship eith your fellow shipmates")
input("one of your shipmates goes to the ships CODEROOM to work on the ship")
input("your shipmate in the CODEROOM gets a weird signal, AN SOS SIGNAL FROM AN UNKNOWN PLANET")
input("the shipmate tells you that the ship is halfway to earth. it was supposed to be there already")
go = input("you are told to board a ship to THE UNKNOWN PLANET. do you go? (y/n)")
if go == "yes": print("i hope this doesnt end up terrible. (foreshadowing)")
else: print("trust dude it will be so fun!!!!")
input("you are having heavy turbulence on the ship but you still land on the planet okay. but the ship is quite damaged")
input("some of the shipmates go down to reroute some ducts on the ship")
input("the same transmission sends every 12 seconds.")
input("the atmosphere is apparently very deadly")
input("your shipmates go outside.")
input("you are now one of the outsidemates")
input("outside is a cold desolate wasteland. outside you can barely see.")
input("you see a strange metal structure. it is solid and you go inside")
climb = input("you have the abiliy to climb the walls. do you do this? (y/n)")
if climb == "yes": print("you climb")
else: print("okay so you dont but another crewmate does")
input("HE SAYS THERE IS LIFE.")
input(" you branch off from the rest of the team and discover...")
input("EGGS.")
input("inside there is organic life inside the egg.")
input("THE EGG OPENS AND...")
input("you are now the shipmate from earlier. your name is ripley")
open = input("you are told to open the doors. the other shipmates say that an organism attached itself to another shipmate. do you open (y/n) ")
if open == "yes": print("you open the doors.")
else: print("you are forced to.")
input("they try to remove the strange creature from his face. they are unsucsesfull.")
input("they try to remove it another way, buts it spits out ACID")
input("the acid begins melting through the deck but stops.")
input("they seal THE INFECTED ONE in a room by himself")
input("THE CREATURE is incredibly strong and resistant.")
input("the creature suddently removed itself from THE INFECTED ONES face.")
input("THE CREATURE LAND ON YOUR FACE")
input("it isnt fully attached so youre good. in fact, ITS DEAD")
launch = input("the ship is still quite broken but your captain insists you take off. do you? (y/n)")
if launch == "yes": print("YOU HAVE LAUNCHED")
else: print("HE IS THE CAPTAIN. YOU LAUNCH")
input("you tell the crew that they will all (including you) have to go back into quarintine on earth")
input("you and the crew go to check on THE INFECTED ONE. he is okay")
input("you all go to dinner. you all want to have good food on earth")
input("he starts CHOKING... UNTIL...")
input("A CREATURE BURSTS OUT OF HIS STOMACH")
input("IT IS A TINY CREATURE WITH A SMALL MOUTH. BEFORE YOU KNOW IT, IT RUNS AWAY.")
input("you send the dead ones body into space.")
input("you are split up into teams to capture the creature. you are given a weapon")
input("you walk around the ship and get an airsignal that it is 5 meters away from you")
input("you notice the area where it is and try to capture it")
input("it was just a cat... :D")
input("one member goes off to find the cat")
input("you are now the catsearcher")
input("you find the cat. and SHEDDED SKIN")
input("you continue searching for the cat because it ran away")
input("you see the cat hiding and........")
input("THE ALIEN IS BEHIND YOU")
#you are dead, not big suprise.
input("you are now ripley")
input("you go back to the main point and learn that the alien might die when near fire")
#no shit sherlock
input("you are now the coderoom guy")
input("NOTHINGISCOMPUTINGNOTHINGISCOMPUTINGNOTHINGISCOMPUTINGNOTHINGISCOMPUTINGNOTHINGISCOMPUTING")
input("you go into the vents with a flamethrower")
input("you ask ripley to open the vents.")
input("ripley loses signal with the creature.")
input("IT COMES BACK ONLINE.")
input("IT IS RIGHT UNDER Y")
input("you are now ripley.")
input("Lambert (another crewmate) is being a cowering loser looooooooooooooooooooollllllll (shes actually being kinda rational im just trolling)")
input("you tell everyone to split into groups and try to find the alien through the air vents.")
input("you go to the ships coderoom and see")
input("BRING BACK ORGANISM. CREW EXPENDABLE")
#this is absolute bullfucking shit so yeah
input("the crews science officer attacks you")
#mistreating women is fucking ass bro
input("he throws you around the room and TRIES TO KILL YOU")
#little fucker.
input("HE STARTS SPEWING WHITE GOO AND... HE IS A ROBOT.")
input("parker, another member of your crew says, ASH IS A GODDAMN ROBOT")
#peak line btw
input("the crew fixes the robot and the robot repeats")
input("BRING BACK ORGANISM. CREW EXPENDABLE")
#fucking bullshit bro
input("YOU  DECIDE TO BLOW UP THE SHIP")
input("you, lambert, and parker go to blow up the ship")
input("YOU HAVE SEVEN MINUTES")
input("you go to get the rocket ready to launch")
input("you go to try and find the cat, Jones.")
input("you hear rattling")
input("jones runs as you catch him")
input("you are now parker")
input("THE ALIEN IS RIGHT BY LAMBERT")
input("IT GRABS YOU AND.")
input("LAMBERT AND PARKER ARE DEAD")
input("you are ripley")
input("you run to them and see them...")
#dead
input("you run to try and blow up the ship... it works")
input("You must run.")
input("YOU HAVE TEN MINUTES")
input("YOU GRAB THE CAT AND RUN AS FAST AS YOU CAN")
#RUN BITCH RUNNNNNNNNNNNNNNNNNNNNNN
input("7 Minutes")
#you can hear th e music playing
input("IT IS RUNNING BEHIND YOU")
input("5 MINUTES")
input("YOU RUN IN THE FOGGY SHIP TO THE ROCKET")
input("YOU HAVE LOST TRACK OF TIME. IT IS DEAFENING ON THE SHIP")
input("YOU ARE ON THE ROCKET")
input("1 MINUTE")
input("30 SECONDS")
input("5")
input("4")
input("3")
input("2")
input("1-")
input("you have left. the ship has exploded. you are okay")
#and the cat is too!!!!!!!!!! YAY!!!!!!!!!!!!!!!!!!!!!!!!
input("your cat goes into hypersleep.. but... THE ALIEN FOLLOWED YOU ON THE ROCKET")
KILLALIEN = input("your final descision... fight? (y/n)")
if KILLALIEN == "yes": print("You put on spacesuit for extra protection and... KILL")
else: print("well ya try to at least.")
input("YOU SEND IT OUT THE AIRLOCK. IT TRIES TO CLIMB IN AGAIN BUT YOU BLAST IT INTO SPACE")
input("all of your crew is dead. cargo and ship destroyed.")
input("you are going back to earth")
input("you and your cat are in hypersleep")
input("onward, to earth")
print("thank you for playing")
input("from BLITZ")